/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces_graficas;

import armazenamento.FichaDao;
import fichas.FichaBD;
import fichas.FichaResumidaBD;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.Point;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.Border;

/**
 *
 * @author lucas
 */
public class Pesquisa extends javax.swing.JFrame {
    FichaDao bd = new FichaDao();
    DefaultListModel modelo = new DefaultListModel();
    DefaultListModel modelo2 = new DefaultListModel();
    ArrayList<FichaResumidaBD> list;
    /**
     * Creates new form Pesquisa
     */
    public Pesquisa() {
        initComponents();
        scrollLista.setSize(783,550);
        URL camin = getClass().getResource("/interfaces_graficas/imagens/simbolo.png");
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(camin));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barraPesquisa = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        scrollLista = new javax.swing.JScrollPane(listaPessoas);
        listaPessoas = new javax.swing.JPanel();
        carregaDados(bd.getTudo());
        voltarPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pesquisaPanel = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(191, 191, 191));
        jPanel1.setPreferredSize(new java.awt.Dimension(790, 680));

        barraPesquisa.setBackground(new java.awt.Color(191, 191, 191));
        barraPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        barraPesquisa.setBorder(null);
        barraPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        barraPesquisa.setPreferredSize(new java.awt.Dimension(487, 20));
        barraPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraPesquisaActionPerformed(evt);
            }
        });
        barraPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                barraPesquisaKeyReleased(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        scrollLista.getViewport().setView(listaPessoas);
        scrollLista.setBorder(null);
        scrollLista.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        listaPessoas.setBackground(new java.awt.Color(191, 191, 191));

        javax.swing.GroupLayout listaPessoasLayout = new javax.swing.GroupLayout(listaPessoas);
        listaPessoas.setLayout(listaPessoasLayout);
        listaPessoasLayout.setHorizontalGroup(
            listaPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        listaPessoasLayout.setVerticalGroup(
            listaPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        scrollLista.setViewportView(listaPessoas);

        voltarPanel.setBackground(new java.awt.Color(191, 191, 191));
        voltarPanel.setPreferredSize(new java.awt.Dimension(50, 50));
        voltarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                voltarPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                voltarPanelMouseReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces_graficas/imagens/voltar.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout voltarPanelLayout = new javax.swing.GroupLayout(voltarPanel);
        voltarPanel.setLayout(voltarPanelLayout);
        voltarPanelLayout.setHorizontalGroup(
            voltarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(voltarPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );
        voltarPanelLayout.setVerticalGroup(
            voltarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pesquisaPanel.setBackground(new java.awt.Color(191, 191, 191));
        pesquisaPanel.setPreferredSize(new java.awt.Dimension(40, 40));
        pesquisaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pesquisaPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pesquisaPanelMouseReleased(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces_graficas/imagens/lupa pequena.png"))); // NOI18N
        jLabel29.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout pesquisaPanelLayout = new javax.swing.GroupLayout(pesquisaPanel);
        pesquisaPanel.setLayout(pesquisaPanelLayout);
        pesquisaPanelLayout.setHorizontalGroup(
            pesquisaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesquisaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        pesquisaPanelLayout.setVerticalGroup(
            pesquisaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollLista, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(voltarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(barraPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(voltarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(barraPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addComponent(pesquisaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollLista)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarPanelMouseReleased
        voltarPanel.setBackground(new Color(240,240,240));
        Home home = new Home();
        Point location = this.getLocation();
        home.setLocation(location);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarPanelMouseReleased

    private void voltarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarPanelMousePressed
        voltarPanel.setBackground(new Color(170,170,170));
    }//GEN-LAST:event_voltarPanelMousePressed

    private void pesquisaPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaPanelMousePressed
        pesquisaPanel.setBackground(new Color(160,160,160));
    }//GEN-LAST:event_pesquisaPanelMousePressed

    private void pesquisaPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaPanelMouseReleased
        pesquisaPanel.setBackground(new Color(191,191,191));
        ArrayList<FichaResumidaBD> listaPesquisa = bd.pesquisa(barraPesquisa.getText());
        if (listaPesquisa != null) carregaDados(listaPesquisa);
        else zeraDados();
    }//GEN-LAST:event_pesquisaPanelMouseReleased

    private void barraPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barraPesquisaKeyReleased
        if (barraPesquisa.getText().length() == 0){
            ArrayList<FichaResumidaBD> listaPesquisa = bd.getTudo();
            carregaDados(listaPesquisa);
        }
    }//GEN-LAST:event_barraPesquisaKeyReleased

    private void barraPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraPesquisaActionPerformed
        ArrayList<FichaResumidaBD> listaPesquisa = bd.pesquisa(barraPesquisa.getText());
        if (listaPesquisa != null) carregaDados(listaPesquisa);
        else zeraDados();
    }//GEN-LAST:event_barraPesquisaActionPerformed
    
    private static class RoundedBorder implements Border {     
        private int radius;
        private Color cor;
        
        RoundedBorder(int radius,Color cor) {
            this.radius = radius;
            this.cor = cor;
        }
        @Override
        public Insets getBorderInsets(Component c) {
            return new Insets(this.radius+1, this.radius+1, this.radius+2, this.radius);
        }

        @Override
        public boolean isBorderOpaque() {
            return true;
        }

        @Override
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            g.setColor(cor);
            g.fillRoundRect(x,y,width,height,radius,radius);
        }
        
        public Color getCor(){
            return cor;
        }
    }    
    
    public void itemMousePressed(java.awt.event.MouseEvent evt, JPanel panel){
        RoundedBorder borda = (RoundedBorder) panel.getBorder();
        Color cor = borda.getCor();
        panel.setBorder(new RoundedBorder(10,cor.darker()));
    }
    
    public void itemMouseReleased(java.awt.event.MouseEvent evt,JPanel panel, String numMatricula){
        RoundedBorder borda = (RoundedBorder) panel.getBorder();
        Color cor = borda.getCor();
        panel.setBorder(new RoundedBorder(10,cor.brighter()));
        FichaPesquisa fichaPesquisa = new FichaPesquisa();
        fichaPesquisa.fichaEscolhida = bd.getFicha(numMatricula);
        fichaPesquisa.origem = 0;
        fichaPesquisa.carregaFicha();
        Point location = this.getLocation();
        fichaPesquisa.setLocation(location);
        fichaPesquisa.setVisible(true);
        this.dispose();
    }
    
    public void carregaDados(ArrayList<FichaResumidaBD> listaPesquisa){
        zeraDados();
        int y = 0;

        if (listaPesquisa != null){
            for (FichaResumidaBD ficha : listaPesquisa) {
                JPanel panel = new JPanel();
                panel.setBorder(new RoundedBorder(10,ficha.getCor()));
                panel.setBackground(new Color(191,191,191));
                panel.setBounds(10, y, 740, 45);

                JLabel nomeLabel = new JLabel(ficha.getNome());
                nomeLabel.setFont(new Font("Tahoma", Font.PLAIN, 20));
                nomeLabel.setBounds(30, y + 2, 500, 25);


                listaPessoas.add(nomeLabel);
                listaPessoas.add(panel);
                y += 50;


                if (y >= 600){
                    Dimension nDim = new Dimension(listaPessoas.getWidth(),y);
                    listaPessoas.setSize(nDim);
                    listaPessoas.setPreferredSize(nDim);
                } 

                panel.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mousePressed(java.awt.event.MouseEvent evt) {
                        itemMousePressed(evt,panel);
                    }
                    public void mouseReleased(java.awt.event.MouseEvent evt) {
                        itemMouseReleased(evt,panel,ficha.getNumMatricula());
                    }
                });
            }
            if (y < 600){
                Dimension nDim = new Dimension(listaPessoas.getWidth(),586);
                listaPessoas.setSize(nDim);
                listaPessoas.setPreferredSize(nDim);
            } 
        }
    }
    
    public void zeraDados(){
        Component[] components = listaPessoas.getComponents();
        
        for (Component component : components) {
            component.setBounds(0, 0, 0, 0);
            component = null;
        }
        listaPessoas.removeAll();
    }
    
    public void montarListapesquisa(JList<String> lista, JScrollPane scroll){
        String nomePesquisar = barraPesquisa.getText();
        ArrayList<FichaBD> list = bd.pesquisa(nomePesquisar);
        
        modelo.removeAllElements();
        
        if (list != null)
            for(FichaBD f: list){
                modelo.addElement(f.getNome());
            }
            
            if(!modelo.isEmpty()){
                int max = 211;
                int calc = 21 + 19*(list.size()-1);
                if(calc > max) calc = max; 
                lista.setSize(487,calc);
                scroll.setSize(487,calc);
                lista.setVisible(true);
                scroll.setVisible(true);
            }else{
                lista.setVisible(false);
                scroll.setVisible(false);
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel listaPessoas;
    private javax.swing.JPanel pesquisaPanel;
    private javax.swing.JScrollPane scrollLista;
    private javax.swing.JPanel voltarPanel;
    // End of variables declaration//GEN-END:variables
}
