/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces_graficas;

import armazenamento.FichaDao;
import fichas.FichaResumidaBD;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.Point;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author lucas
 */
public class Vencimento extends javax.swing.JFrame {
    FichaDao bd = new FichaDao();
   
    public Vencimento() {
        initComponents();
        carregaDados();
        URL camin = getClass().getResource("/interfaces_graficas/imagens/simbolo.png");
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(camin));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        voltarPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaVencimento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(32767, 32767));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 700));

        jPanel1.setBackground(new java.awt.Color(191, 191, 191));

        voltarPanel.setBackground(new java.awt.Color(191, 191, 191));
        voltarPanel.setPreferredSize(new java.awt.Dimension(50, 50));
        voltarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                voltarPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                voltarPanelMouseReleased(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces_graficas/imagens/voltar.png"))); // NOI18N

        javax.swing.GroupLayout voltarPanelLayout = new javax.swing.GroupLayout(voltarPanel);
        voltarPanel.setLayout(voltarPanelLayout);
        voltarPanelLayout.setHorizontalGroup(
            voltarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(voltarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        voltarPanelLayout.setVerticalGroup(
            voltarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");

        listaVencimento.setBackground(new java.awt.Color(191, 191, 191));

        javax.swing.GroupLayout listaVencimentoLayout = new javax.swing.GroupLayout(listaVencimento);
        listaVencimento.setLayout(listaVencimentoLayout);
        listaVencimentoLayout.setHorizontalGroup(
            listaVencimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );
        listaVencimentoLayout.setVerticalGroup(
            listaVencimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(listaVencimento);

        jLabel1.setText("NOME E TELEFONE");

        jLabel2.setText("DIA DO VENCIMENTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(voltarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(172, 172, 172))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void voltarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarPanelMousePressed
        voltarPanel.setBackground(new Color(170,170,170));
    }//GEN-LAST:event_voltarPanelMousePressed

    private void voltarPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarPanelMouseReleased
        voltarPanel.setBackground(new Color(240,240,240));
        Home home = new Home();
        Point location = this.getLocation();
        home.setLocation(location);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarPanelMouseReleased
    private static class RoundedBorder implements Border {
        
        private int radius;
        private Color cor;
        
        RoundedBorder(int radius,Color cor) {
            this.radius = radius;
            this.cor = cor;
        }
        @Override
        public Insets getBorderInsets(Component c) {
            return new Insets(this.radius+1, this.radius+1, this.radius+2, this.radius);
        }

        @Override
        public boolean isBorderOpaque() {
            return true;
        }

        @Override
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            g.setColor(cor);
            g.fillRoundRect(x,y,width,height,radius,radius);
        }
        
        public Color getCor(){
            return cor;
        }
    }
    
    public void itemMousePressed(java.awt.event.MouseEvent evt, JPanel panel){
        RoundedBorder borda = (RoundedBorder) panel.getBorder();
        Color cor = borda.getCor();
        panel.setBorder(new RoundedBorder(10,cor.darker()));
        
    }
    
    public void itemMouseReleased(java.awt.event.MouseEvent evt,JPanel panel, String numMatricula){
        RoundedBorder borda = (RoundedBorder) panel.getBorder();
        Color cor = borda.getCor();
        panel.setBorder(new RoundedBorder(10,cor.brighter()));
        FichaPesquisa fichaPesquisa = new FichaPesquisa();
        fichaPesquisa.fichaEscolhida = bd.getFicha(numMatricula);
        fichaPesquisa.origem = 1;
        fichaPesquisa.carregaFicha();
        Point location = this.getLocation();
        fichaPesquisa.setLocation(location);
        fichaPesquisa.setVisible(true);
        this.dispose();
    }
    
    
    public void carregaDados(){
        FichaDao bd = new FichaDao();
        ArrayList<FichaResumidaBD> listaPesquisa = bd.getListaVencimento();
        int y = 0;
        
        if (listaPesquisa != null)
            for (FichaResumidaBD ficha : listaPesquisa) {
                JPanel panel = new JPanel(); 
                panel.setBorder(new RoundedBorder(10,ficha.getCor()));
                panel.setBackground(new Color(191,191,191));
                panel.setBounds(10, y, 740, 45);
                JLabel nomeLabel = new JLabel(ficha.getNome());
                nomeLabel.setFont(new Font("Tahoma", Font.PLAIN, 20));
                nomeLabel.setBounds(30, y + 2, 500, 25);

                JLabel telefoneLabel = new JLabel(ficha.getTelefone());
                telefoneLabel.setFont(new Font("Tahoma", Font.PLAIN, 15));
                telefoneLabel.setBounds(30, y + 22, 500, 20);

                JLabel diaLabel = new JLabel(Integer.toString(ficha.getDiaVencimento()));
                diaLabel.setFont(new Font("Tahoma", Font.PLAIN, 20));
                diaLabel.setBounds(540, y , 48, 48);

                listaVencimento.add(nomeLabel);
                listaVencimento.add(telefoneLabel);            
                listaVencimento.add(diaLabel);
                listaVencimento.add(panel);
                y += 50;

                if (y >= 600){
                    Dimension nDim = new Dimension(listaVencimento.getWidth(),y);
                    listaVencimento.setSize(nDim);
                    listaVencimento.setPreferredSize(nDim);
                } 

                panel.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mousePressed(java.awt.event.MouseEvent evt) {
                        itemMousePressed(evt,panel);
                    }
                    public void mouseReleased(java.awt.event.MouseEvent evt) {
                        itemMouseReleased(evt,panel,ficha.getNumMatricula());
                    }
                });
            }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vencimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vencimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vencimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vencimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vencimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel listaVencimento;
    private javax.swing.JPanel voltarPanel;
    // End of variables declaration//GEN-END:variables
}
